### ISSUE TITLE
[Enhancement] Add CI workflow as Github Action w/ security linting/scanning

### ISSUE THREAD

**Issue by weklund** [Voyz/ibind#45]
> template pulled from https://github.com/Voyz/ibeam/blob/master/.github/ISSUE_TEMPLATE/enhancement.md

**Describe the feature**

Enable flake8 (for linting) and bandit (for security checks) in GitHub Actions to improve code quality and security as a CI (continuous integration) step. Initially, the workflow will be informative and non-blocking. Once we gain trust in the signal, we can enforce these checks to block PRs until issues are resolved.

**Expected interaction**

- When a PR is created or updated, the CI workflow will trigger and run linting with [Flake8](https://flake8.pycqa.org/en/latest/) and security scanning with [bandit](https://bandit.readthedocs.io/en/1.8.2/index.html)
- **Initially**, test results will be informative only and not block merges.
- As confidence in the workflow/scanning grows, we can toggle it to block PRs at some point in time.
- In the future, we can expand CI to include testing and test coverage as mentioned here https://github.com/Voyz/ibind/pull/34#discussion_r1939613275

Example: .github/workflows/ci.yml:
```
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ibind CI workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"      # <---- unknown if we need to change or add multiple versions/runs

    #----------------------------------------------
    #       Load cached venv if cache exists
    #----------------------------------------------
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --exclude ./.venv/lib --max-complexity=10
        continue-on-error: true
    #----------------------------------------------
    #         Run security scans (TODO: Get Github advanced security)
    #----------------------------------------------
    - name: Perform Bandit Analysis
      run: |
        bandit -r . -ll
      continue-on-error: true
```

**Possible implications**

- This feature introduces automated checks that could surface existing security issues and linting errors
- We can iterate on this through multiple PRs as we learn more.

**Additional context**

There is currently no CONTRIBUTING.md file in the repository to provide guidance on contributing. I'm open to feedback on how best to help out :)
